version: "3.9"
services:
  client:
    container_name: client
    restart: always
    build: ./client
    ports: 
      - "3000:3000"
    links:
      - app
  app:
    container_name: app
    restart: always
    build: ./server
    ports:
      - "3001:3001"
    